---
name: Audit

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  audit:
    runs-on: ubuntu-20.04
    name: Audit
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '3.27'
          - '3.28'
          - '3.29'
          - master

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --pre c2cciutils[audit]

      - name: Audit
        run: c2cciutils-audit --branch=${{ matrix.branch }}

      - run: ./gradlew dependencyCheckAnalyze
