---
name: Audit

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Audit
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '3.20'
          - '3.21'
          - '3.22'
          - '3.23'
          - '3.24'
          - '3.25'

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ matrix.branch }}

      - run: ./gradlew dependencyCheckAnalyze
