---
name: Rebuild 3.20 - 3.22

on:
  schedule:
    - cron: '0 0 * * *'

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  rebuild:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    name: Rebuild 3.20 - 3.22

    env:
      SUMMON_PROVIDER: /usr/local/bin/gopass

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '3.20'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker
      - run: gpg --export-secret-keys --armor D121AF2DFA8E140688BD968930C9B913FD42EF13 > CI.asc

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - name: Install OS dependencies
        run: sudo apt install fonts-liberation

      - uses: actions/setup-java@v3
        with:
          java-version: 8

      - name: Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v3
        with:
          name: Test results
          path: core/build/resources/
          if-no-files-found: ignore
        if: failure()
      - uses: actions/upload-artifact@v3
        with:
          name: Reports examples
          path: examples/build/reports
          if-no-files-found: ignore
        if: failure()
      - uses: actions/upload-artifact@v3
        with:
          name: Reports core
          path: core/build/reports
          if-no-files-found: ignore
        if: failure()
      - uses: actions/upload-artifact@v3
        with:
          name: Examples
          path: examples/build/resources/test/examples
          if-no-files-found: ignore
        if: failure()

      - run: ./gradlew createDocker

      - name: Publish
        run: c2cciutils-publish
        if: env.HAS_SECRETS == 'HAS_SECRETS'
